
[general]
	#If true, allow basic movement inputs while the EZActions radial is open.
	moveWhileRadialOpen = false
	#How many lines are shown in the command editor text box (visual only).
	#Range: 1 ~ 32
	commandEditorVisibleLines = 6

