
["Skill Points"]
	#Range: 1 ~ 1000
	"Maximum skill points" = 999
	#Range: > 0
	"First skill point cost" = 160
	#Range: > 0
	"Last skill point cost" = 4339720 
	#You can set cost for each skill point instead
	"Use skill points costs array" = true
	#This list's size must be equal to maximum skill points.
	"Levelup costs" = [160,160,160,160,160,160,160,160,160,160,160,160,160,160,160,160,160,160,160,160,160,160,160,160,160,315,315,315,315,315,315,315,315,315,315,315,315,315,315,315,315,315,315,315,315,315,315,315,315,315,550,550,550,550,550,550,550,550,550,550,550,550,550,550,550,550,550,550,550,550,550,550,550,550,550,910,910,910,910,910,910,910,910,910,910,910,910,910,910,910,910,910,910,910,910,910,910,910,910,910,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,1395,4339720 ,4339720 ]
	#Disabling this will remove chat messages when you gain a skill point.
	"Show chat messages" = true
	#Warning: If you disable this make sure you make alternative way of getting skill points.
	"Enable exprerience exchange for skill points" = true

["Amnesia Scroll"]
	#How much levels (percentage) player lose using amnesia scroll
	#Range: 0.0 ~ 1.0
	"Amnesia scroll penalty" = 0.2
	"Drop amnesia scrolls from the Ender Dragon" = true

[Experience]
	#Range: 0.0 ~ 1.0
	"Grindstone experience multiplier" = 0.1

