onCull = false
MaxEntityEntities = 256
qualityModes = "NORMAL"
RenderWeather = "NORMAL"
FastItemRender = false
RenderDisplayItem = false
blackListedEntities = []
whiteListedEntities = []
isAlwaysShowItemCount = false
startTime = 164.665
chatFix = false
onGui = false
GuiRXTX = false
GuiFPS = true
GuiCPU = false
GuiGPU = false
GuiRAM = false
GuiEntityCount = false
GuiPlayerPos = false
GuiServer = false
GuiCameraTarget = false
Mood = false
Particle = true
BlockBreakParticleMode = "NORMAL"
MaxParticleDistance = 152
WhiteListedParticle = []
BlackListedParticle = []
FPSMonitor = false
GuiEasyRamMode = false
GuiDisplayRamUsage = false
GuiX = 0
GuiY = 0
EntityRender = true
UseAui = false
DeBug = false
TextBackground = false
TextureAnimatedSprites = true
SoundDevicesMonitor = false
SetParticleMaxAge = false
ParticleMaxAge = 1
GuiViewMode = "NULL"
EntityCullFov = 160
MinDistance = 5
EntityDistance = 188
TickPerformance = false
